Src/Litium.Accelerator.Mvc/Controllers/Framework/ClientContextController.cs
using System.Web.Mvc;
using Litium.Accelerator.Builders.Framework;

namespace Litium.Accelerator.Mvc.Controllers.Framework
{
    public class ClientContextController : ControllerBase
    {
        private readonly ClientContextViewModelBuilder _clientContextViewModelBuilder;

        public ClientContextController(ClientContextViewModelBuilder clientContextViewModelBuilder)
        {
            _clientContextViewModelBuilder = clientContextViewModelBuilder;
        }

        [ChildActionOnly]
        public ActionResult Index()
        {
            var viewModel = _clientContextViewModelBuilder.Build();
            return PartialView("Framework/ClientContext", viewModel);
        }
    }
}

Src/Litium.Accelerator.Mvc/Controllers/Framework/LayoutController.cs
using System.Web.Mvc;
using Litium.Accelerator.ViewModels.Framework;
using Litium.Accelerator.Builders.Framework;
using Litium.Web.Models.Websites;
using Litium.Web.Models.Products;
using Litium.Accelerator.Constants;
using System.Web;
using Litium.Accelerator.Utilities;
using Litium.Products;

namespace Litium.Accelerator.Mvc.Controllers.Framework
{
    /// <summary>
    /// LayoutController renders views for the layout (header,foter,BreadCrumbs)
    /// </summary>
    public class LayoutController : ControllerBase
    {
        private readonly HeadViewModelBuilder<HeadViewModel> _headViewModelBuilder;
        private readonly HeaderViewModelBuilder<HeaderViewModel> _headerViewModelBuilder;
        private readonly BreadCrumbsViewModelBuilder<BreadCrumbsViewModel> _breadCrumbsViewModelBuilder;
        private readonly FooterViewModelBuilder<FooterViewModel> _footerViewModelBuilder;
        private readonly BodyViewModelBuilder _bodyViewModelBuilder;
        private readonly MarketSelectorViewModelBuilder<MarketSelectorViewModel> _marketSelectorViewModelBuilder;
        private readonly CookieNotificationViewModelBuilder<CookieNotificationViewModel> _cookieNotificationViewModelBuilder;
        private readonly FavoritesViewModelBuilder<FavoritesViewModel> _favoritesViewModelBuilder;
        private readonly DisplayTemplateService _displayTemplateService;

        public LayoutController(
            BreadCrumbsViewModelBuilder<BreadCrumbsViewModel> breadCrumbsViewModelBuilder,
            HeadViewModelBuilder<HeadViewModel> headViewModelBuilder,
            HeaderViewModelBuilder<HeaderViewModel> headerViewModelBuilder,
            FooterViewModelBuilder<FooterViewModel> footerViewModelBuilder,
            BodyViewModelBuilder bodyViewModelBuilder,
            MarketSelectorViewModelBuilder<MarketSelectorViewModel> marketSelectorViewModelBuilder,
            CookieNotificationViewModelBuilder<CookieNotificationViewModel> cookieNotificationViewModelBuilder,
            FavoritesViewModelBuilder<FavoritesViewModel> favoritesViewModelBuilder,
            DisplayTemplateService displayTemplateService)
        {
            _breadCrumbsViewModelBuilder = breadCrumbsViewModelBuilder;
            _headViewModelBuilder = headViewModelBuilder;
            _headerViewModelBuilder = headerViewModelBuilder;
            _footerViewModelBuilder = footerViewModelBuilder;
            _bodyViewModelBuilder = bodyViewModelBuilder;
            _marketSelectorViewModelBuilder = marketSelectorViewModelBuilder;
            _cookieNotificationViewModelBuilder = cookieNotificationViewModelBuilder;
            _favoritesViewModelBuilder = favoritesViewModelBuilder;
            _displayTemplateService = displayTemplateService;
        }

        [ChildActionOnly]
        public ActionResult Head(WebsiteModel currentWebsiteModel, PageModel currentPageModel, CategoryModel currentCategory, ProductModel currentProductModel)
        {
            var viewModel = _headViewModelBuilder.Build(currentWebsiteModel, currentPageModel, currentCategory, currentProductModel);
            return PartialView("Framework/Head", viewModel);
        }

        /// <summary>
        /// Builds header for the site
        /// </summary>
        /// <returns>Return view for the header</returns>
        [ChildActionOnly]
        public ActionResult Header()
        {
            var viewModel = _headerViewModelBuilder.Build();
            return PartialView("Framework/Header", viewModel);
        }

        [ChildActionOnly]
        public ActionResult BodyEnd(WebsiteModel currentWebsiteModel, PageModel currentPageModel, CategoryModel currentCategory, ProductModel currentProductModel)
        {
            var viewModel = _bodyViewModelBuilder.BuildBodyEnd(currentWebsiteModel, currentPageModel, currentCategory, currentProductModel);
            return PartialView("Framework/BodyEnd", viewModel);
        }

        [ChildActionOnly]
        public ActionResult BodyStart(WebsiteModel currentWebsiteModel, PageModel currentPageModel, CategoryModel currentCategory, ProductModel currentProductModel)
        {
            var viewModel = _bodyViewModelBuilder.BuildBodyStart(currentWebsiteModel, currentPageModel, currentCategory, currentProductModel);
            return PartialView("Framework/BodyStart", viewModel);
        }

        /// <summary>
        /// Builds bread crumbs for the site
        /// </summary>
        /// <param name="currentPageModel">The current page</param>
        /// <param name="categoryModel">The current category</param>
        /// <param name="currentProductModel">The current product</param>
        /// <param name="startLevel">Defines from which level the breadcrumbs will be rendered</param>
        /// <returns>Return view for the bread crumbs</returns>
        [ChildActionOnly]
        public ActionResult BreadCrumbs(PageModel currentPageModel, CategoryModel categoryModel, ProductModel currentProductModel, int startLevel = 0)
        {
            var viewModel = _breadCrumbsViewModelBuilder.BuildBreadCrumbs(currentPageModel, categoryModel, currentProductModel, startLevel);
            return PartialView("Framework/BreadCrumbs", viewModel);
        }

        [ChildActionOnly]
        public ActionResult Footer()
        {
            var viewModel = _footerViewModelBuilder.Build();
            return PartialView("Framework/Footer", viewModel);
        }

        [ChildActionOnly]
        public ActionResult MarketSelector(bool isMobile = false)
        {
            var viewModel = _marketSelectorViewModelBuilder.Build();

            var viewPath = isMobile ? "Framework/MarketSelectorMobile" : "Framework/MarketSelector";
            return PartialView(viewPath, viewModel);
        }

        [ChildActionOnly]
        public ActionResult CookieNotification()
        {
            var viewModel = _cookieNotificationViewModelBuilder.Buid();
            viewModel.ShouldRender = Request.Cookies[CookieNotificationMessage.CookieName] == null;

            return PartialView("Framework/CookieNotification", viewModel);
        }

        [ChildActionOnly]
        public ActionResult Favorites()
        {
            var model = new FavoritesViewModel();

            var cookie = Request.Cookies[FavoritesConstants.FavoritesCookieName];
            if(cookie != null)
            {
                var variantSystemIds = Request.Cookies[FavoritesConstants.FavoritesCookieName]?.Value ?? string.Empty;
                if (!string.IsNullOrEmpty(variantSystemIds))
                {
                    var decodedValue = HttpUtility.UrlDecode(variantSystemIds);
                    model = _favoritesViewModelBuilder.Build(decodedValue.Split(','));
                }
            }

            return PartialView("Framework/Favorites", model);
        }
    }
}

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/BodyStart.cshtml
@model Litium.Accelerator.ViewModels.Framework.BodyStartViewModel
@Html.Raw(Model.TrackingScripts)

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/BreadCrumbs.cshtml
@model Litium.Accelerator.ViewModels.Framework.BreadCrumbsViewModel

@if (Model.ContentLinks != null && Model.ContentLinks.Any())
{
    <nav aria-label="breadcrumb" class="d-none d-md-block px-5 pt-3">
        <ol class="breadcrumb">
            @foreach (var contentLink in Model.ContentLinks)
            {
                <li class="breadcrumb-item @(contentLink.IsSelected? $"active" : $"")" @(contentLink.IsSelected ? "aria-current='page'" : string.Empty)>
                    <a href="@contentLink.Url">@contentLink.Name</a>
                </li>
            }
        </ol>
    </nav>
}

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/CookieNotification.cshtml
@using Litium.Studio.Extenssions;
@using Litium.Web.Mvc;
@model Litium.Accelerator.ViewModels.Framework.CookieNotificationViewModel

@if (Model.ShouldRender)
{
	<div class="cookieNotification modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropCookie" aria-hidden="true">
		<div class="modal-dialog modal-lg modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-body border border-2 border-secondary p-4">
					<div class="container-fluid">
						<div class="row">
							@if (!string.IsNullOrEmpty(Model.Title))
							{
								<div class="col-12"><h3>@Model.Title</h3></div>
								<div class="col-3"><hr /></div><div class="col-9"></div>
							}
							@if (!string.IsNullOrEmpty(Model.Text))
							{
								<div class="col-12 col-lg-9">
									<p>
										@Model.Text
										@if (Model.PolicyPage != null)
										{
											<text> - </text><a class="text-decoration-underline" href="@Model.PolicyPage.Href">@Model.PolicyPage.Text</a>
										}
									</p>
								</div>
								<div class="d-none d-lg-flex col-lg-3">
									<figure class="cookie-logo">@Html.ImageFor(x => x.Logo, maxSize: new Size(160, 100))</figure>
								</div>
							}
							<div class="col-12">
								<div class="input-group">
									<input type="button" class="cookieNotificationBtn btn btn-dark me-3" data-accept="true" value="@Html.WebSiteString("cookieconsent.accept")" />
									<input type="button" class="cookieNotificationBtn btn btn-info text-white" data-accept="false" value="@Html.WebSiteString("cookieconsent.reject")" />
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
}

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/Favorites.cshtml
@model Litium.Accelerator.ViewModels.Framework.FavoritesViewModel

<div class="offcanvas offcanvas-end" tabindex="-1" id="favorites" aria-labelledby="favoritesLabel">

	<!-- Header -->
	<div class="offcanvas-header bg-dark">
		<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
	</div>

	<div class="offcanvas-body">
		<h3 class="mt-3">@Html.WebSiteString("favorites.header")</h3>
		<hr />
		<ul class="list-group mb-3 favorites-list">
			@foreach (var product in Model.Products)
			{
				<li class="list-group-item border-0 d-flex align-items-center justify-content-between">
					<a href="@product.Url">
						<p class="mb-0">@product.Name</p>
					</a>
					<a class="deletefavorites-btn cursor-hover">
						<i class="bi bi-trash" data-variantid="@product.Id"></i>
					</a>
				</li>
			}
		</ul>
	</div>
</div>

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/Head.cshtml
@model Litium.Accelerator.ViewModels.Framework.HeadViewModel
@using Litium.Web.Mvc

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@Model.Title</title>
@Url.FingerprintStylesheetTag("/ui/css/site.min.css", useQueryHash: true)
@foreach (var fav in Model.Favicons)
{
    <link rel="@fav.Rel" href="@fav.Href" type="@fav.Type" />
}
@if (!string.IsNullOrWhiteSpace(Model.MetaDescription))
{
    <meta name="description" content="@Model.MetaDescription" />
}

@if (!string.IsNullOrWhiteSpace(Model.Canonical))
{
    <link rel="canonical" href="@Model.Canonical" />
}

@if (!string.IsNullOrWhiteSpace(Model.MetaRobots))
{
    <meta name="robots" content="@Model.MetaRobots" />
}
<meta name="generator" content="Litium" />
@if (Model.OpenGraph != null)
{
    @Html.Partial("Framework/_OpenGraph", Model.OpenGraph)
}

@Html.Raw(Model.TrackingScripts)

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/Header.cshtml
@model Litium.Accelerator.ViewModels.Framework.HeaderViewModel
@using Litium.Web.Mvc

@{
	var hasGetOrganisedCTA = !string.IsNullOrEmpty(Model.GetOrganised.Href);
}

<header id="header" role="banner" class="header">

	<nav class="navbar navbar-expand-lg border-bottom border-dark border-1 py-2 d-none d-lg-flex bg-dark">
		<div class="container">
			<div class="collapse navbar-collapse me-auto">
				<ul class="navbar-nav">
					@Html.Partial("Framework/TopLink", Model)
				</ul>
			</div>

			<div class="d-flex align-items-center">
				<div class="marketselector dropdown">
					@Html.Action("MarketSelector", "Layout")
				</div>

				<div class="ms-3" id="quickSearch"></div>
			</div>
		</div>
	</nav>

	<nav class="navbar navbar-expand-lg py-2 px-3 px-lg-0 linear-bg">
		<div class="container">
			<a class="navbar-brand me-5" href="@Model.StartPageUrl">
				@Html.ImageFor(x => x.Logo, maxSize: new System.Drawing.Size(-1, 50))
			</a>

			@if (Model.Categories != null && Model.Categories.Any())
			{
				<div class="collapse navbar-collapse">
					<ul class="navbar-nav">
						@foreach (var category in Model.Categories)
						{
							<li class="nav-item px-4">
								<div class="megamenu dropdown text-uppercase">
									@Html.Partial("Framework/Subcategory", category)
								</div>
							</li>
						}
					</ul>
				</div>
			}

		<div class="d-flex align-items-center justify-content-around util-items">
			<a href="#" data-bs-toggle="offcanvas" data-bs-target="#favorites" aria-controls="favorites">
				<i class="bi bi-heart"></i>
			</a>

			@Html.Partial("Framework/Profile", Model)

			@*<div id="miniCart" class="cart cart--mini"><i class="bi bi-bag"></i></div>*@
			
			<button class="hamburger hamburger--slider d-inline-block d-md-none ms-4" type="button" data-bs-toggle="offcanvas" data-bs-target="#mobileMenu" aria-controls="mobileMenu">
				<span class="hamburger-box">
					<span class="hamburger-inner"></span>
				</span>
			</button>
		</div>
			@if (hasGetOrganisedCTA)
			{
				<a class="btn btn-link btn-cta-link mx-5 text-uppercase d-none d-lg-block" href="@Model.GetOrganised.Href" title="@Model.GetOrganised.Text">
					@Model.GetOrganised.Text
				</a>
			}
		</div>
	</nav>

	<nav class="navbar d-lg-none justify-content-between p-3 linear-bg-small">
		<div class="container d-flex justify-content-end">
			@if (hasGetOrganisedCTA)
			{
				<a class="btn btn-link btn-cta-link text-uppercase" href="@Model.GetOrganised.Href" title="@Model.GetOrganised.Text">
					@Model.GetOrganised.Text
				</a>
			}
		</div>
	</nav>
</header>


<!-- MOBILE MENU -->
<div class="offcanvas offcanvas-start w-100 dark" tabindex="-1" id="mobileMenu" aria-labelledby="mobileMenuLabel">
	<!-- Header -->
	<div class="offcanvas-header bg-dark">
		<a class="navbar-brand me-5" href="@Model.StartPageUrl">
			@Html.ImageFor(x => x.Logo, maxSize: new System.Drawing.Size(-1, 50))
		</a>
		<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
	</div>

	<div class="offcanvas-body p-0 pb-4 bg-dark">
		<!-- Search -->
		<div class="linear-bg-small py-1 px-2">
			<div id="quickSearchMobile"></div>
		</div>

		<!-- Main categories -->
		@if (Model.Categories != null && Model.Categories.Any())
		{
			<ul class="list-group mb-3 px-3 pt-5 bg-transparent">
				@foreach (var category in Model.Categories)
				{
					<li class="list-group-item border-0 bg-transparent"><a href="@category.Url"><h2 class="text-uppercase text-white">@category.Name</h2></a></li>
				}
			</ul>
		}

		<ul class="list-group border-0 mb-2 px-3 bg-transparent">
			@if (hasGetOrganisedCTA)
			{
				<li class="list-group-item border-0 bg-transparent">
					<a href="@Model.GetOrganised.Href" class="fw-bold text-uppercase link-primary cta-mobile-menu" title="@Model.GetOrganised.Text">
						@Model.GetOrganised.Text
					</a>
				</li>
			}
			@if (Model.TopLinkList.Any())
			{
				foreach (var link in Model.TopLinkList)
				{
					if (link != null)
					{
						<li class="list-group-item border-0 bg-transparent">
							<a href="@link.Href" class="fw-bold text-white">
								@link.Text
							</a>
						</li>
					}
				}
			}
		</ul>
		<hr />
		<!-- Utils -->
		<ul class="list-group border-0 mobile-utils mt-2 px-3">
			<li class="list-group-item border-0 bg-transparent"><a class="d-flex align-items-center" href="#" data-bs-toggle="offcanvas" data-bs-target="#favorites" aria-controls="favorites"><i class="bi bi-heart me-3"></i><p class="text-white mb-1">@Html.WebSiteString("general.mobilenavigation.favorites")</p></a></li>
			
			@Html.Partial("Framework/ProfileMobile", Model)

			<!-- marketselector -->
		</ul>

		<div class="dropup">@Html.Action("MarketSelector", "Layout", new { isMobile = true })</div>
	</div>
</div>

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/MarketSelector.cshtml
@model Litium.Accelerator.ViewModels.Framework.MarketSelectorViewModel

@if (Model.ChannelLinkList.Any() && Model.ChannelLinkList.Count > 1)
{
	var current = Model.ChannelLinkList.FirstOrDefault(link => link.IsSelected);

	var uneven = Model.ChannelLinkList.Count % 2 == 1;
	var half = Model.ChannelLinkList.Count / 2;

	var firstRow = uneven ? Model.ChannelLinkList.Skip(0).Take(half + 1) : Model.ChannelLinkList.Skip(0).Take(half);
	var secondRow = uneven ? Model.ChannelLinkList.Skip(half + 1).Take(half) : Model.ChannelLinkList.Skip(half).Take(half);

	<a href="#" class="nav-link dropdown-toggle" id="navbarMarketsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
		@if (current != null)
		{
			<span class="text-white">@current.Name</span>
		}
		<i class="arrow arrow-down arrow-primary"></i>
	</a>
	<ul class="dropdown-menu dropdown-menu-marketselector" aria-labelledby="navbarMarketsDropdown">
		<li class="bg-white border-bottom border-dark border-1">
			<div class="container">
				<div class="clearfix"><div class="media close mt-3 float-end"></div></div>
				<div class="row pb-4">
					<div class="col-md-8">
						<div class="row">
							<div class="col-12"><h3 class="px-3">@Html.WebSiteString("marketselector.markets.header")</h3></div>
							<div class="col-md-6">
								<ul class="list-group list-group-flush">
									@foreach (var link in firstRow)
									{
										if (link != null)
										{
											<li class="list-group-item vertical-align-tb">@Html.ImageFor(x => x.ChannelLinkList.First(channelLink => channelLink == link).Image, maxSize: new System.Drawing.Size(29, 19))<a class="ms-3" href="@link.Url">@link.Name</a></li>
										}
									}
								</ul>
							</div>
							<div class="col-md-6">
								<ul class="list-group list-group-flush">
									@foreach (var link in secondRow)
									{
										if (link != null)
										{
											<li class="list-group-item vertical-align-tb">@Html.ImageFor(x => x.ChannelLinkList.First(channelLink => channelLink == link).Image, maxSize: new System.Drawing.Size(29, 19))<a class="ms-3" href="@link.Url">@link.Name</a></li>
										}
									}
								</ul>
							</div>
						</div>
					</div>
					<div class="col-md-4">
						<div class="row">
							<div class="col-12"><h3 class="px-3">@Html.WebSiteString("marketselector.partners.header")</h3></div>
							<div class="col-12">
								<ul class="list-group list-group-flush">
									@foreach (var link in Model.PartnerLinkList)
									{
										if (link != null)
										{
											<li class="list-group-item vertical-align-tb">@Html.ImageFor(x => x.PartnerLinkList.First(partner => partner == link).Image, maxSize: new System.Drawing.Size(29, 19))<a class="ms-3" href="@link.Url">@link.Name</a></li>
										}
									}
								</ul>
							</div>
						</div>
					</div>
				</div>
				

			</div>
		</li>
	</ul>
}

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/MarketSelectorMobile.cshtml
@model Litium.Accelerator.ViewModels.Framework.MarketSelectorViewModel
@if (Model.ChannelLinkList.Any() && Model.ChannelLinkList.Count > 1)
{
	var current = Model.ChannelLinkList.FirstOrDefault(link => link.IsSelected);

	<a href="#" class="nav-link dropdown-toggle" id="navbarMarketsMobileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
		@if (current != null)
		{
			<span>@current.Name</span>
		}
		<i class="arrow arrow-up arrow-primary"></i>
	</a>
	<ul class="dropdown-menu dropdown-mobilemenu-marketselector" aria-labelledby="navbarMarketsMobileDropdown">
		<li><h4>@Html.WebSiteString("mobilemarket.channels.title")</h4></li>
		@foreach (var link in Model.ChannelLinkList)
		{
			<li class="vertical-align-tb py-3">@Html.ImageFor(x => x.ChannelLinkList.First(channelLink => channelLink == link).Image, maxSize: new System.Drawing.Size(29, 19))<a class="ms-3" href="@link.Url">@link.Name</a></li>
		}

		<li><hr /></li>
		<li><h4>@Html.WebSiteString("mobilemarket.partner.title")</h4></li>
		
		@foreach (var partner in Model.PartnerLinkList)
		{
			<li class="vertical-align-tb py-3">@Html.ImageFor(x => x.PartnerLinkList.First(partnerLink => partnerLink == partner).Image, maxSize: new System.Drawing.Size(29, 19))<a class="ms-3" href="@partner.Url">@partner.Name</a></li>
		}
	</ul>
}

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/Profile.cshtml
@using Litium.Accelerator.ViewModels.Framework;
@model HeaderViewModel

@{
	var currentPage = User.Identity.IsAuthenticated ? Model.MyPage : Model.LoginPage;
	var href = User.Identity.IsAuthenticated ? currentPage.Href : Model.ExternalB2BLink;
	var text = User.Identity.IsAuthenticated ? currentPage.Text : "external b2b";
}

@if (!string.IsNullOrEmpty(href))
{
	<a href="@href" title="@text" target="@(User.Identity.IsAuthenticated ? "_self" : "_blank")">
		<i class="bi bi-person"></i>
	</a>
}

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/ProfileMobile.cshtml
@using Litium.Accelerator.ViewModels.Framework;
@model HeaderViewModel

@{
	var currentPage = User.Identity.IsAuthenticated ? Model.MyPage : Model.LoginPage;
	var href = User.Identity.IsAuthenticated ? currentPage.Href : Model.ExternalB2BLink;
	var text = User.Identity.IsAuthenticated ? currentPage.Text : "external b2b";
}

@if (!string.IsNullOrEmpty(href))
{
	<li class="list-group-item border-0 bg-transparent">
		<a class="d-flex align-items-center" href="@href" title="@text" target="@(User.Identity.IsAuthenticated ? "_self" : "_blank")">
			<i class="bi bi-person me-3"></i><p class="text-white mb-1">@Html.WebSiteString("general.mobilenavigation.profile")</p>
		</a>
	</li>
}

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/Subcategory.cshtml
@model Litium.Accelerator.ViewModels.Framework.ContentLinkModel


@if (Model.Links.Any())
{
    var current = Model.Name;

    var uneven = Model.Links.Count % 2 == 1;
    var half = Model.Links.Count / 2;

    var firstRow = uneven ? Model.Links.Skip(0).Take(half + 1) : Model.Links.Skip(0).Take(half);
    var secondRow = uneven ? Model.Links.Skip(half + 1).Take(half) : Model.Links.Skip(half).Take(half);

    <a href="#" class="nav-link dropdown-toggle" id="navbarSubCategoryDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        @if (current != null)
        {
            @current
        }
    </a>
    <ul class="dropdown-menu dropdown-menu-megamenu" aria-labelledby="navbarSubCategoryDropdown">
        <li class="bg-white border-bottom border-dark border-1">
            <div class="container">
                <div class="clearfix"><div class="media close mt-3 float-end"></div></div>
                <div class="row pb-4">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-12"><a href="@Model.Url"><h6 class="px-3 text-primary"> @current</h6></a></div>
                            <div class="col-md-5">
                                <ul class="list-group list-group-flush">
                                    @foreach (var link in firstRow)
                                    {
                                        if (link != null)
                                        {
                                            <li class="list-group-item vertical-align-tb"><a class="ms-3" href="@link.Url">@link.Name</a></li>
                                        }
                                    }
                                </ul>
                            </div>
                            <div class="col-md-5">
                                <ul class="list-group list-group-flush">
                                    @foreach (var link in secondRow)
                                    {
                                        if (link != null)
                                        {
                                            <li class="list-group-item vertical-align-tb"><a class="ms-3" href="@link.Url">@link.Name</a></li>
                                        }
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="row">
                            <div class="col-12"><h6 class="px-3"></h6></div>
                            <div class="col-12">
                                <ul class="list-group list-group-flush">
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    </ul>
} 

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/TopLink.cshtml
@using Litium.Accelerator.ViewModels.Framework;
@model HeaderViewModel

@if (Model.TopLinkList.Any()) {
	foreach (var link in Model.TopLinkList) {
		if (link != null) {
			<li class="nav-item me-3">
				<a class="nav-link" href="@link.Href">
					@link.Text
				</a>
			</li>
		}
    }
}

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/_BlockContainer.cshtml
@model List<Litium.Web.Models.Blocks.BlockModel>

@foreach (var item in Model)
{
    <section data-litium-block-id="@item.SystemId">
        @Html.Block(item)
    </section>
}

Src/Litium.Accelerator.Mvc/Views/Shared/Framework/_OpenGraph.cshtml
@model Litium.Accelerator.ViewModels.Framework.OpenGraphViewModel
   
<meta property="og:title" content="@Model.Title" />
<meta property="og:type" content="website" />
@if (Model.ImageVisible)
{
    var suffix = "og:image" + Model.ImageSuffix;
    <meta property="@suffix" content="@Model.ImageUrl" />
}
@if (Model.LogotypeVisible)
{
    var suffix = "og:image" + Model.ImageSuffix;
    <meta property="@suffix" content="@Model.LogotypeImageUrl" />
}
<meta property="og:url" content="@Model.Url" />
<meta property="og:description" content="@Html.Encode(Model.MetaDescription)" />
<meta property="og:locale" content="@Model.Locale" />
<meta property="og:site_name" content="@Model.WebSiteTitle" />